// Homepage and app shared content. Add new popup news here once so both surfaces update together.
window.HARMONY_LINK_SHARED_CONTENT = {
  featuredPrograms: [
    {id:"hibelle-digital",emoji:"💻",ko:"하이벨 디지털",en:"Hibelle Digital",category:"디지털",tagsKo:"스마트폰 · AI · 컴퓨터 교육",tagsEn:"Smartphone · AI · Computer",color:"#dbeaff",image:"/assets/brands/hibelle-digital.jpg",url:"/#specialty-banners"},
    {id:"hibelle-english",emoji:"🌍",ko:"하이벨 화상영어",en:"Hibelle Online English",category:"언어",tagsKo:"1:1 맞춤 화상영어 · 전문 강사진",tagsEn:"Personalized 1:1 online English",color:"#ffe3cf",image:"/assets/brands/hibelle-online-english.jpg",url:"/#specialty-banners"},
    {id:"meeran-melody",emoji:"🎵",ko:"미란멜로디",en:"Meeran Melody",category:"음악",tagsKo:"합창 · 발성 · 음악 교육",tagsEn:"Choir · Voice · Music",color:"#f8dce8",image:"/assets/brands/meeran-melody-logo.png?v=20260819-1",url:"/#specialty-banners"}
  ],
  promotions: [
    {kind:"benefit",badgeKo:"기간 한정 혜택",badgeEn:"LIMITED BENEFIT",titleKo:"PREMIUM 파트너",titleEn:"PREMIUM Partners",textKo:"2026년 8월 31일까지 프리미엄 파트너로 접수하면<br>3개월 등록비 면제 혜택을 드립니다.",textEn:"Apply as a PREMIUM partner by August 31, 2026.<br>Receive a three-month registration fee waiver.",image:"/assets/harmony-logo.png",url:"/#community",actionKo:"함께하기",actionEn:"Join Us"},
    {kind:"program",badgeKo:"전문 수업 안내",badgeEn:"SPECIALTY PROGRAM",titleKo:"하이벨 디지털",titleEn:"Hibelle Digital",textKo:"AI와 스마트폰을 실생활에서 자신 있게 활용하도록 돕는 맞춤형 디지털 교육입니다. 연락처 929-603-0052",textEn:"Practical digital education for using AI and smartphones.<br>Contact 929-603-0052",image:"/assets/brands/hibelle-digital.jpg",url:"/#specialty-banners",actionKo:"수업 보기",actionEn:"View Program"},
    {kind:"program",badgeKo:"전문 수업 안내",badgeEn:"SPECIALTY PROGRAM",titleKo:"하이벨 화상영어",titleEn:"Hibelle Online English",textKo:"시간과 장소의 제약 없이 수준과 목표에 맞춰 진행하는 1:1 실용 화상영어입니다. 연락처 929-603-0052",textEn:"Personalized one-to-one practical English lessons.<br>Contact 929-603-0052",image:"/assets/brands/hibelle-online-english.jpg",url:"/#specialty-banners",actionKo:"수업 보기",actionEn:"View Program"},
    {kind:"program",badgeKo:"전문 수업 안내",badgeEn:"SPECIALTY PROGRAM",titleKo:"미란멜로디",titleEn:"Meeran Melody",textKo:"노래·발성·호흡과 다양한 음악 활동으로 마음과 공동체를 잇는 힐링 프로그램입니다. 연락처 817-905-3468",textEn:"A healing music program connecting hearts and community.<br>Contact 817-905-3468",image:"/assets/brands/meeran-melody-logo.png?v=20260819-1",url:"/#specialty-banners",actionKo:"수업 보기",actionEn:"View Program"},
    {kind:"advertising",badgeKo:"프리미엄 광고 등록",badgeEn:"NEW PREMIUM ADVERTISER",titleKo:"Yura Kim<small>High Line Residential</small>",titleEn:"Yura Kim<small>High Line Residential</small>",textKo:"뉴욕 부동산 에이전트 유라 김<br>좋은 매물 선정부터 계약과 입주까지 함께합니다.<br>연락처 516-390-1383",textEn:"New York real estate agent Yura Kim.<br>Contact 516-390-1383",image:"/assets/ads/highline-hl-symbol.png",url:"https://www.hlres.com/yura-kim",actionKo:"업체 바로가기",actionEn:"Visit Business"},
    {kind:"advertising",badgeKo:"프리미엄 광고 등록",badgeEn:"NEW PREMIUM ADVERTISER",titleKo:"올가닉 원 유기농원",titleEn:"OrganicOne",textKo:"유아동 식품·유기농 건강식품·한국 전통 식품을<br>팰팍과 플러싱 매장에서 만나보세요.<br>연락처 팰팍 201-585-0958 · 플러싱 929-845-0958",textEn:"Organic children’s foods, health foods, and Korean traditional foods.<br>Contact Palisades Park 201-585-0958 · Flushing 929-845-0958",image:"/assets/ads/organic-one/logo-green.png",url:"https://www.organiconestore.com/",actionKo:"업체 바로가기",actionEn:"Visit Business"},
    {kind:"advertising",badgeKo:"프리미엄 광고 등록",badgeEn:"NEW PREMIUM ADVERTISER",titleKo:"HOLE19 골프라운지",titleEn:"HOLE19 Golf Lounge",textKo:"최신 골프 시뮬레이터와 커피·맥주·음식을 함께 즐기는<br>골프라운지입니다. 연락처 929-766-0088",textEn:"A premium golf lounge with modern simulators.<br>Contact 929-766-0088",image:"/assets/ads/hole19/logo.png?v=20260819-1",url:"https://www.instagram.com/hole19_golflounge/",actionKo:"인스타그램 보기",actionEn:"View Instagram"},
    {kind:"community",badgeKo:"협력업체 등록",badgeEn:"NEW COMMUNITY PARTNER",titleKo:"아시안 아메리칸 사법 경찰자문위원회",titleEn:"Asian American Law Enforcement Advisory Council",textKo:"아시안 커뮤니티와 사법기관의 소통과 협력을 지원합니다.<br>연락처 646-996-8093",textEn:"Supporting communication between Asian American communities and law enforcement.",image:"/assets/partners/aaleac-shield.png?v=20260819-1",url:"https://aaleac.org/",actionKo:"업체 바로가기",actionEn:"Visit Business"},
    {kind:"community",badgeKo:"협력업체 등록",badgeEn:"NEW COMMUNITY PARTNER",titleKo:"장수 데이케어",titleEn:"Jangsu Daycare",textKo:"어르신 한 분 한 분을 가족처럼 모시며 건강하고 행복한 하루를 함께하는 데이케어 센터입니다.<br>연락처 718-799-0133 · 718-864-6430",textEn:"A daycare center caring for each senior like family.<br>Phone 718-799-0133 · 718-864-6430",image:"/assets/partners/jangsu-daycare-logo.png?v=20260815-304",url:"tel:+17187990133",actionKo:"전화 바로걸기",actionEn:"Call Now"}
  ]
};
