-- Partner-only community board with row-level security.
begin;

create table if not exists public.partner_community_posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  category text not null check (category in ('notice', 'intro', 'question', 'review', 'resource')),
  title text not null check (char_length(btrim(title)) between 2 and 120),
  content text not null check (char_length(btrim(content)) between 2 and 5000),
  resource_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.partner_community_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.partner_community_posts(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  content text not null check (char_length(btrim(content)) between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists partner_community_posts_created_idx on public.partner_community_posts(created_at desc);
create index if not exists partner_community_posts_category_idx on public.partner_community_posts(category, created_at desc);
create index if not exists partner_community_comments_post_idx on public.partner_community_comments(post_id, created_at);

create or replace function public.is_active_partner_or_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select exists (
    select 1 from public.member_profiles profile
    where profile.id = p_user_id
      and profile.account_status = 'active'
      and profile.role in ('partner0', 'partner20', 'partner50', 'admin')
  );
$$;

create or replace function public.is_active_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select exists (
    select 1 from public.member_profiles profile
    where profile.id = p_user_id
      and profile.account_status = 'active'
      and profile.role = 'admin'
  );
$$;

create or replace function public.set_partner_community_author()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  profile_role text;
  profile_status text;
  verified_name text;
begin
  select profile.role, profile.account_status,
    coalesce(nullif(btrim(profile.display_name), ''),
      nullif(user_account.raw_user_meta_data ->> 'full_name', ''),
      nullif(user_account.raw_user_meta_data ->> 'name', ''),
      split_part(user_account.email::text, '@', 1))
  into profile_role, profile_status, verified_name
  from public.member_profiles profile
  join auth.users user_account on user_account.id = profile.id
  where profile.id = auth.uid();

  if profile_status <> 'active' or profile_role not in ('partner0', 'partner20', 'partner50', 'admin') then
    raise exception 'active partner access required' using errcode = '42501';
  end if;
  if tg_table_name = 'partner_community_posts' and new.category = 'notice' and profile_role <> 'admin' then
    raise exception 'only administrators can publish notices' using errcode = '42501';
  end if;

  if tg_op = 'UPDATE' then
    new.author_id := old.author_id;
    new.author_name := old.author_name;
    new.updated_at := now();
    return new;
  end if;

  new.author_id := auth.uid();
  new.author_name := verified_name;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_partner_community_post_author on public.partner_community_posts;
create trigger set_partner_community_post_author
before insert or update on public.partner_community_posts
for each row execute function public.set_partner_community_author();

drop trigger if exists set_partner_community_comment_author on public.partner_community_comments;
create trigger set_partner_community_comment_author
before insert or update on public.partner_community_comments
for each row execute function public.set_partner_community_author();

alter table public.partner_community_posts enable row level security;
alter table public.partner_community_comments enable row level security;

drop policy if exists partner_posts_read on public.partner_community_posts;
create policy partner_posts_read on public.partner_community_posts for select
  to authenticated using (public.is_active_partner_or_admin());
drop policy if exists partner_posts_insert on public.partner_community_posts;
create policy partner_posts_insert on public.partner_community_posts for insert
  to authenticated with check (public.is_active_partner_or_admin() and author_id = auth.uid());
drop policy if exists partner_posts_update on public.partner_community_posts;
create policy partner_posts_update on public.partner_community_posts for update
  to authenticated using (author_id = auth.uid() or public.is_active_admin())
  with check (author_id = auth.uid() or public.is_active_admin());
drop policy if exists partner_posts_delete on public.partner_community_posts;
create policy partner_posts_delete on public.partner_community_posts for delete
  to authenticated using (author_id = auth.uid() or public.is_active_admin());

drop policy if exists partner_comments_read on public.partner_community_comments;
create policy partner_comments_read on public.partner_community_comments for select
  to authenticated using (public.is_active_partner_or_admin());
drop policy if exists partner_comments_insert on public.partner_community_comments;
create policy partner_comments_insert on public.partner_community_comments for insert
  to authenticated with check (public.is_active_partner_or_admin() and author_id = auth.uid());
drop policy if exists partner_comments_update on public.partner_community_comments;
create policy partner_comments_update on public.partner_community_comments for update
  to authenticated using (author_id = auth.uid() or public.is_active_admin())
  with check (author_id = auth.uid() or public.is_active_admin());
drop policy if exists partner_comments_delete on public.partner_community_comments;
create policy partner_comments_delete on public.partner_community_comments for delete
  to authenticated using (author_id = auth.uid() or public.is_active_admin());

revoke all on public.partner_community_posts from anon;
revoke all on public.partner_community_comments from anon;
grant select, insert, update, delete on public.partner_community_posts to authenticated;
grant select, insert, update, delete on public.partner_community_comments to authenticated;
grant usage, select on sequence public.partner_community_posts_id_seq to authenticated;
grant usage, select on sequence public.partner_community_comments_id_seq to authenticated;
grant execute on function public.is_active_partner_or_admin(uuid) to authenticated;
grant execute on function public.is_active_admin(uuid) to authenticated;

commit;
